import type { GymClass, ScheduledSession } from "@/types";

export const classes: GymClass[] = [
  {
    id: "strength-foundations",
    slug: "strength-foundations",
    name: "Strength Foundations",
    shortDescription:
      "Learn the main movement patterns with attentive coaching.",
    fullDescription:
      "A small-group introduction to bracing, hinging, squatting, pressing, and carrying. Coaches scale loading while keeping the whole room on one clear technical focus.",
    duration: 60,
    intensity: "Moderate",
    experienceLevel: "Beginner",
    maximumCapacity: 8,
    trainerIds: ["coach-one"],
    equipment: ["Barbells", "Kettlebells", "Benches"],
    image: "/images/forge-hero.webp",
    accentLabel: "Start here",
    active: true,
  },
  {
    id: "forge-strength",
    slug: "forge-strength",
    name: "FORGE Strength",
    shortDescription: "Progressive strength work built around the major lifts.",
    fullDescription:
      "A coached strength block that pairs one principal lift with accessible assistance work. Demonstration programming shows how progression and adaptable loading can live in one class.",
    duration: 75,
    intensity: "High",
    experienceLevel: "Intermediate",
    maximumCapacity: 10,
    trainerIds: ["coach-one", "coach-two"],
    equipment: ["Barbells", "Racks", "Dumbbells"],
    image: "/images/forge-hero.webp",
    accentLabel: "Build strength",
    active: true,
  },
  {
    id: "engine",
    slug: "engine",
    name: "Engine",
    shortDescription:
      "Conditioning that supports performance rather than noise.",
    fullDescription:
      "Mixed-modal intervals using rowers, bikes, and sleds. Work periods are scalable, technique remains visible, and intensity never replaces intent.",
    duration: 50,
    intensity: "High",
    experienceLevel: "All levels",
    maximumCapacity: 12,
    trainerIds: ["coach-two"],
    equipment: ["Rowers", "Bikes", "Sleds"],
    image: "/images/forge-hero.webp",
    accentLabel: "Conditioning",
    active: true,
  },
  {
    id: "mobility-recovery",
    slug: "mobility-recovery",
    name: "Mobility + Recovery",
    shortDescription: "Controlled movement, range, and recovery work.",
    fullDescription:
      "A lower-intensity session combining controlled range, breathing, and gentle loading. It is a training class, not medical treatment or rehabilitation.",
    duration: 45,
    intensity: "Low",
    experienceLevel: "All levels",
    maximumCapacity: 12,
    trainerIds: ["coach-one"],
    equipment: ["Mats", "Bands", "Foam rollers"],
    image: "/images/forge-hero-mobile.webp",
    accentLabel: "Recover",
    active: true,
  },
];

export const sampleSessions: ScheduledSession[] = [
  {
    id: "mon-foundations",
    classId: "strength-foundations",
    trainerId: "coach-one",
    date: "2026-08-31",
    startTime: "07:00",
    endTime: "08:00",
    timeZone: "Asia/Beirut",
    capacity: 8,
    bookedCount: 3,
    status: "Available",
    recurring: true,
    mock: true,
  },
  {
    id: "mon-strength",
    classId: "forge-strength",
    trainerId: "coach-two",
    date: "2026-08-31",
    startTime: "18:00",
    endTime: "19:15",
    timeZone: "Asia/Beirut",
    capacity: 10,
    bookedCount: 8,
    status: "Nearly full",
    recurring: true,
    mock: true,
  },
  {
    id: "tue-engine",
    classId: "engine",
    trainerId: "coach-two",
    date: "2026-09-01",
    startTime: "17:30",
    endTime: "18:20",
    timeZone: "Asia/Beirut",
    capacity: 12,
    bookedCount: 12,
    status: "Waitlist",
    recurring: true,
    mock: true,
  },
  {
    id: "wed-mobility",
    classId: "mobility-recovery",
    trainerId: "coach-one",
    date: "2026-09-02",
    startTime: "19:30",
    endTime: "20:15",
    timeZone: "Asia/Beirut",
    capacity: 12,
    bookedCount: 4,
    status: "Available",
    recurring: true,
    mock: true,
  },
];

export const getClassBySlug = (slug: string) =>
  classes.find((item) => item.slug === slug && item.active);
